services:
  flask:
    build: ./project_1
    container_name: flask-app

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: "mysql+pymysql://root:root@mysql:3306/testdb"
      FLASK_SECRET_KEY: "my-secret-key"
      JWT_SECRET_KEY: "my-jwt-secret-key"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"

    depends_on:
      - flask

    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    ports:
      - "3001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
      - loki
      - tempo

    networks:
      - app-network

  mysql:
    image: mysql:9.6.0
    container_name: mysql_dbs

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki

    ports:
      - "3100:3100"

    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml

    command:
      - "-config.file=/etc/loki/local-config.yaml"

    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail

    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

    command:
      - "-config.file=/etc/promtail/config.yml"

    depends_on:
      - loki

    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo

    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml

    command:
      - "-config.file=/etc/tempo.yaml"

    depends_on:
      - flask

    networks:
      - app-network

volumes:
  mysql-data:
  grafana-data:

networks:
  app-network:
