apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  DATABASE_URL: mysql+pymysql://root:root@mysql-service:3306/testdb
  FLASK_SECRET_KEY: my-secret-key
  JWT_SECRET_KEY: my-jwt-secret-key
